APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:VzPzgcICpR/SnJeQX7Z+ZxrSVQOF0I8ATY8SumgRkIQ=
APP_DEBUG=true
APP_URL=https://fundmylaptopteamsaint.herokuapp.com

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=us-cdbr-east-02.cleardb.com
DB_PORT=3306
DB_DATABASE=heroku_b155a2f06611b26
DB_USERNAME=b26e5a4e97c2ed
DB_PASSWORD=1ab3b199

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

FB_CLIENT_ID=
FB_CLIENT_KEY=
FB_REDIRECT_URL=

LI_CLIENT_ID=
LI_CLIENT_KEY=
LI_REDIRECT_URL=
